// One-off: download the `latin` woff2 subset for our three families from Google
// Fonts and emit public/fonts.css with @font-face rules. Self-hosted = offline-safe.
const fs = require('fs');
const path = require('path');

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const OUT = path.join(__dirname, '..', 'public', 'fonts');
fs.mkdirSync(OUT, { recursive: true });

// family display name, css family param, weights, local file slug
const FAMILIES = [
  { name: 'Fraunces', param: 'Fraunces:opsz,wght@9..144,400;9..144,600;9..144,900', slug: 'fraunces' },
  { name: 'Hanken Grotesk', param: 'Hanken+Grotesk:wght@400;500;700', slug: 'hanken' },
  { name: 'Space Mono', param: 'Space+Mono:wght@400;700', slug: 'spacemono' },
];

async function run() {
  let css = '/* self-hosted fonts — generated by scripts/fetch-fonts.js */\n';
  for (const fam of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${fam.param}&display=swap`;
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    const text = await res.text();
    // Split into @font-face blocks, keep only the `/* latin */` ones.
    const blocks = text.split('/*').map((b) => '/*' + b);
    let n = 0;
    for (const b of blocks) {
      if (!/^\/\*\s*latin\s*\*\//.test(b)) continue; // latin only, skip latin-ext/cyrillic/etc
      const weightMatch = b.match(/font-weight:\s*([0-9]+)/);
      const styleMatch = b.match(/font-style:\s*(\w+)/);
      const urlMatch = b.match(/url\((https:[^)]+\.woff2)\)/);
      if (!urlMatch) continue;
      const weight = weightMatch ? weightMatch[1] : '400';
      const style = styleMatch ? styleMatch[1] : 'normal';
      const file = `${fam.slug}-${weight}.woff2`;
      const buf = Buffer.from(await (await fetch(urlMatch[1], { headers: { 'User-Agent': UA } })).arrayBuffer());
      fs.writeFileSync(path.join(OUT, file), buf);
      css += `@font-face{font-family:'${fam.name}';font-style:${style};font-weight:${weight};font-display:swap;src:url('/fonts/${file}') format('woff2');}\n`;
      n++;
      console.log('saved', file, buf.length, 'bytes');
    }
    if (!n) console.warn('!! no latin block found for', fam.name);
  }
  fs.writeFileSync(path.join(__dirname, '..', 'public', 'fonts.css'), css);
  console.log('\nwrote public/fonts.css');
}
run().catch((e) => { console.error(e); process.exit(1); });
